language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean jbake	

after_success:      
  - cd build/jbake
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages ${TRAVIS_BUILD_NUMBER}"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" origin:master > /dev/null 2>&1

branches:
  only:
  - source

