title=Как приручить Jenkins API
date=2014-11-19
type=post
status=published
summary=Небольшой пост о том, как можно добраться до внутренностей Jenkins.
tags=Jenkins, CI
~~~~~~
Небольшой пост о том, как можно добраться до внутренностей https://jenkins.io/index.html[Jenkins].
Бывают ситуации, когда СI сервер установлен где-то на удаленной машине, доступ к которой осуществляется через VPN. В общем ситуация сложная, а информацию о джобах и письма от дженкинса получать хотелось бы.
В таком случае в помощь приходит https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API[Jenkins API].
API позволяет извлекать информацию в трех форматах XML, JSON и Python.
Как это работает? Очень просто: все что нужно - вбить в браузере в строке адреса:

[source, java]
----
http://<jenkins host>/api/json
----

Вуаля! Круто, не правда ли? Но текст не читабелен. Решается это просто: нужно добавить pretty формат:

[source, java]
----
http://9.21.103.66:8255/jenkins/api/json?pretty=true
----

Теперь на экране в **JSON** формате отображается информация обо всех джобах. Для того, чтобы опуститься на уровень одного **Job**, необходимо просто указать имя:

[source, java]
----
http://<JENKINS_HOST>/job/<JOB_NAME>/api/json?pretty=true
----

А чтобы получить информацию о какой-либо сборке, нужно всего лишь указать ее номер:

[source, java]
----
http://<JENKINS_HOST>/job/<JOB_NAME>/<BUILD_NUMBER>/api/json?pretty=true
----

После получения информации ее можно использовать в благих целях. Но об этом я расскажу в следующий раз...