title=Создаем виртуальную машину в три шага
date=2015-08-09
type=post
status=published
summary=Заметка о том, как можно coздавать виртуалки.
tags=Тест фреймворк, Java
~~~~~~
Хоу-хоу. Новая заметка не заставила себя ждать. Наверняка всем автоматизаторам известна проблема создания тестровых окружений для прогона тестов. Большинство из нас использует для прогона автотестов виртуальные машины. Я зачастую использую **VirtualBox**. Если вы хоть раз пробовали создать виртуалку с нуля, то, вероятно, знаете, что это требует затрат времени и сил. В этой заметке я покажу, как просто и быстро создавать тестовые окружения с помощью инструмента **Vagrant**.

Идея вагранта очень проста: он основывается на наличии готовых базовых образов. В оригинале они называются - **box**. The Tao of Vagrant содержит несколько простых принципов, которые гарантируют то, что созданная вами виртуальная машина будет работать на любой операционной системе: Mac OS, Windows, Linux.

Начнем работать с **Vagrant**.

**Шаг 1: Установка**

Нам потребуется установить **VirtualBox** и собственно **Vagrant**. Скачиваем нужный инсталятор http://www.vagrantup.com/downloads[здесь] и устанавливаем. Инструкция по установке VirtualBox http://www.windxp.com.ru/article9.htm[здесь].

**Шаг 2: Скачиваем готовый box**

Открываем консоль и выполняем команды:

[source, xml]
----
mkdir vm
cd vm
vagrant box add hashicorp/precise32
vagrant init hashicorp/precise32
----

**Шаг 3: Запускаем виртуальную машину:**

[source, java]
----
vagrant up
----

Через несколько секунд у вас поднимется готовая виртуальная машина.

Вот так, затратив всего 10 минут, вы получаете полностью готовую к работе виртуальную машину. Попробуйте - вам понравится. В следующих заметках я покажу, как продолжить настройку созданной машины. Как создавать свои машины, запаковывать их и делиться ими с коллегами по команде. Подписывайтесь, чтобы держать руку на пульсе.
