= Консультации для автоматизаторов
Sergey Pirogov
2018-06-11
:jbake-type: post
:jbake-tags: Обучение
:jbake-summary: Про консультации

Привет! В этом посте решил рассказать о своем опыте консультирования по автоматизации тестирования.

Осознание того, что в  мире автоматизации тестирования нету нормальных ресурсов для обучения
и устранения проблем, которые сложно решить самому, ко мне пришло после сотрудничества с несколькими IT школами.

Сейчас на рынке много предложений для тех, кто хочет войти в сферу IT. Но что делать тем, кто уже работает?
Я сам сталкивался с этой проблемой, когда был джуниором. Ты что-то делаешь на работе, но, бывает, очень сложно понять,
насколько это правильно. В больших компаниях у джуниоров и специалистов среднего уровня зачастую есть
ментор, который может подсказать, что и как. Однако существует огромный пласт компаний, в которых ребята пытаются построить автоматизацию самостоятельно.
Обычно - это самоучки, которые на собственном энтузиазме что-то изучали в интернете или ходили на курсы, а потом начали делать автоматизацию у себя на проекте.
Сталкиваясь с такими кейсами в процессе консультирования, я заметил, что автоматизация тестирования, "построенная на энтузиазме",
без присмотра опытных людей, либо не работает вообще, либо работает не так эффективно, как могла бы.

Именно таким ребятам я и решил помогать решать проблемы,так как имею определенный опыт и могу им поделиться.

*Менторинг:*

https://spirogov.github.io/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/2018/06/08/mentor.html[Менторинг] - это отличный формат, с помощью которого человек может улучшить свои навыки.
У вас в компании нету надлежащей экспертизы и вы сталкиваетесь с какой-то проблемой? Путей решения у вас два.
Первый - неделями гуглить и лопатить книги. Второй - попросить опытного человека помочь.
Часто на курсах, к примеру, решают проблемы группы. Все учат один инструмент с одинаковым подходом. В моем же случае
менторинг предусматривает индивидуальный подход и, в первую очередь, направлен на решение проблемы конкретного человека.

*Персональная консультация:*

Следующий формат - https://spirogov.github.io/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/2016/06/08/consulting.html[персональная консультация].
Это удобно, если человеку нужно решить одну конкретную проблему.
К примеру, настроить CI или создать каркас проекта для автоматизации. Такая штука отлично подходит для людей,
которым просто нужно один раз дать толчок, а дальше они сами смогут разобраться. Мой кейс, когда Docker
только начинал набирать популярность, я не мог понять вообще, что это такое и как оно работает. Я заплатил 100$ и пошел на платный
мастер-класс, на котором мы подробно разобрали вопрос. Знания, полученные тогда, до сих пор помогают мне в моей работе и окупились уже неоднократно.

*Мастер-классы:*

Ну, и наконец я иногда провожу мастер-классы, на которых показываю некоторые практики и подходы, которые
помогают ребятам на их основной работе. Такой формат требует значительных затрат по времени, поэтому мастер-классы случаются редко.
Один из примеров - это мастер-класс по настройке https://www.patreon.com/posts/jenkins-master-18271646[Jenkins CI].

Хочу отметить, что проведение консультаций требует нового уровня знаний и опыта, так как проблему нужно
решать быстро и давать результат. Если на обычной работе вы можете месяцами мудохать 5 тестов, то здесь такая тема не прокатит.
Как плюс для личностного развития - это возможность видеть подходы, решения и инструменты, с которыми раньше не работал.
Как пример http://dredd.org/en/latest/[Dredd] или appium.

Если вам нужна помощь, смело обращайтесь через форму на https://spirogov.github.io/[сайте].
Пишите свои вопросы и я обязательно постараюсь вам помочь.









