= Консультации для автоматизаторов
Sergey Pirogov
2018-06-11
:jbake-type: post
:jbake-tags: Обучение
:jbake-summary: Про консультации

Привет, в этом посте решил рассказать о своем опыте консультирования по автоматизации тестирования.

Осознание того, что в большоим мире автоматизации тестирования нету нормальных ресурсов для обучения
и решения проблем которые сложно решить самому ко мне пришло после сотрудничества с несколькими IT школами.

Сейчас на рынке много предложений для тех кто хочет войти в сферу IT, но что делать тем кто уже работает?
Я сам сталкивался с этой проблемой, когда был джуниором. Зачастую ты что-то делаешь на работе, но очень сложно понять вообще
насколько это правильно. В больших компаниях у джуниоров и специалистов среднего уровня зачастую есть
ментор, который может подсказать что и как. Однако существует огромный плас компаний в которых ребята
работаю самостоятельно и пытаются построить автоматизацию. Обычно - это самоучки которые на собственном
энтузиазме что-то изучали в интернете или ходили на курсы, а потом начали делать автоматизацию у себя на проекте.
Зачастую, сталкиваясь с такими кейсами в процессе консультирования, автоматизация тестирования "построенная на энтузиазме",
без присмотра опытных людей, либо не работает либо работает не так эффективно как могла бы.

Именно таким ребятам я и решил помогать решать проблемы,так как имею определенный опыт и могу с ним поделиться.

https://spirogov.github.io/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/2018/06/08/mentor.html[Менторинг] - это отличный формат с помощью которого человек может улучшить свои навыки.
У вас в компании нету надлежащей экспертизы и вы сталкиваетесь с какой-то проблемой, путей решения у вас два.
Первый - неделями гуглить и лопатить книги. Второй - попросить опытного человека помочь. В моем случае
менторинг предусматривает индивидуальный подход и в первую очередь направлен на решение проблемы конкретного человека.
На курсах к примеру, зачастую, решают проблемы группы. Все учат один инструмент с одинаковым подходом.

Следующий формат - https://spirogov.github.io/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5/2016/06/08/consulting.html[персональная консультация].
По факту - это формат в котором человеку нужно решить одну конкретную проблему.
К примеру, настроить CI или создать каркас проекта для автоматизации. Такая штука отлично подходит для людей,
которым просто нужно один раз дать толчок и дать они смогу сами разобраться. Мой кейс, когда Docker
только начинал набирать популярность я не мог понять вообще, что это такое и как оно работает. Я заплатил 100$ и пошел на платный
мастер-класс на котором мы подробно разобрали вопрос. Знания полученные тогда до сих пор помогают мне в моей работе и окупились уже неоднократно.

Ну и на конец я иногда провожу мастер-классы на которых показываю некоторые практики и подходы, которые
помогают ребятам на их основной работе. Такой формат требует значительных затрат по времени, поэтому мастер классы случаются редко.
Один из примеров - это мастер класс по настройке https://www.patreon.com/posts/jenkins-master-18271646[Jenkins CI].

Хочу отметить, что проведение консультаций требует новый уровень знаний и опыта, так как проблему нужно
решать быстро и давать результат. Если на обычной работе вы можете месяцами мудохать 5 тестов, то здесь такая тема не прокатит.
Как плюс для личносного развития - это возможности видеть подходы, решения и инструменты с которыми раньше не работал.
Как пример http://dredd.org/en/latest/[Dredd] или appium.

Если вы нуждаетесь в помощи смело обращайтесь через форму на https://spirogov.github.io/[сайте].
Пишите свои вопросы и я обязательно постараюсь всем помочь.









