= Тренинг Automation in Action Java
Sergey Pirogov
2018-08-06
:jbake-type: post
:jbake-tags: Тренинг
:jbake-status: published

Появилось время на обучение. Решил запустить обучающую программу.

Эта программа тренинга направлена на практическую составляющую.
Этот курс расчитан не для начинающих. Я ожидаю видеть ребят которые уже работают на проектах и смогут применять полученные знания у себя, не важно даже если вы сейчас работает на позиции Manual QA, но хотите с чего-то начать.

Требования:
- Знания Java. Умение читать и понимать Java код.
- Знание консольных утелит git, linux commands

Чего не будет:
- Основ Java
- Основ операционных систем
- Основ тестирования
- Много теории

Что будет:

- Много практики

- Создание проекта для тетирования REST API.
  - подходы к автоматизации
  - структура проекта
  - управление тестовыми данными

- Создание проекта для тестирования UI
  - подходы к построению "фреймворка"
          на основе как проверенных инструментов, так и альтернативных типа HTMLElements 2
  - подходы к управлению тестовыми данными
  - репортинг

- Настройка CI
  - Gitlab CI
  - Jenkins с пайплайнами и подходом Infrastructure as a code. Jenkins job DSL

- Инфраструктура для автоматизации на основе облачных решений от DigitalOcean.
  - подходы к управлению инфраструктурой.
  - configuration management на основе ansible

- Запуск тестов в Docker контейнерах
   - обзор существующих решений и работа с инструментами которые я использую каждый день

Все это с реальным демо проектом построенным на микросервисной архитектуре.

Цена 300$

Детали можно узнать в telegram *@spirogov* или написав письмо на *automationremarks@gmail.com*