= Эпизод-17: Александр Венгер о том, как стать самым крутым и другие инсайды с тестатонов
2018-07-14
:jbake-type: post
:jbake-tags: QAGuild, Podcast, Conference
:jbake-summary: Запись подкаста c победителем DevChallenge 12
:jbake-status: published

Поймали чемпиона и заставили его рассказать всю правду.

*Темы:*

- Как пришел в IT? Где греб?
- Немного о проекте "Каратель"?
- Как из простого QA Automation перейти в перформанс QA?
- Почему Саше не страшна утечка данных из ФБ?
- Зачем пошел на Dev Challenge?
- Опция участие бесплатно и участие за бабло?
- Про поездку в долину?
- Инсайды есть, что понравилось?
- Какая тактика оказалась выигрышной? Больше багов или круче доки?
- Можно ли после победы идти опять?
- Что дала победа? Научился ли чему-то новому?
- Срыв покровов, что не понравилось в DevChallenge?
- Дали ли +300 после победы?
- Советы тем, кто хочет учавствовать и побеждать

*Гости:*

- Сергей Пирогов - заводила подкаста
- Ярослав Пернеровский - бог звука в подкасте
- Александр Венгер - абсолютный чемпион DevChallenge 12

++++
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/471599028%3Fsecret_token%3Ds-7D9lM&color=%238c8c64&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
++++

++++
<a class="btn btn-primary" role="button" href="https://itunes.apple.com/ua/podcast/qaguild/id1350668092?l=ru&mt=2">Слушать в Itunes</a>
++++

*Спасибо патронам*:

Алиса Маркова, Алексей Игнатюк, Алексей Асанов, Дмитрий Панасюк, Борис Осипов,
Павел Скворцов, Эрик Халимов, Геннадий Мирошниченко, Михаил Судья, Виталий Закорчевный, Максим Денисов, Татьяна Грибок, Арина Аригри, Олег Ильицкий, Роман Поботин

Отдельное спасибо за монтаж звука Ярославу Пернеровскому