= QA Guild Podcast #15: Про тестатоны
Sergey Pirogov
2018-07-01
:jbake-type: post
:jbake-tags: QAGuild, Podcast
:jbake-summary: QA Guild Podcast
:jbake-status: published

Душевный разговор про тестатоны.

*Темы:*

- Что такое тестатон и что там делают?
- Когда это вообще появилось в наших широтах?
- Кто организовывает тестатоны и зачем это им это нужно?
- Какая причина похода на тестатон, как участника?
- Можно ли на тестатоне чему-то научиться новому?
- Как стать судьей?
- Что дает проектам которые тестируют?
- Дает ли что-нибудь победа? Деньги, опыт, строчка в резюме
- Можно ли после победы сразу просить +300
- Хантят ли победителей тестатона прям там?
- Почему мало тестатонов по автоматизации?

*Гости:*

- Сергей Пирогов - вошел в IT через галеру
- Ярослав Пернеровский - вошел в IT как нормальный человек
- Александр Ищенко - принимал участие в тастатонах в качестве участника и теперь является членом орг. коммитета тестатона для стартапов TestUAStartups.
- Анна Чернышова - работает в Альфа-Банке, одна из создателей библиотеки akita и с ней же победила на тестатоне в Вильнюсе
- Евгений Клименко - неоднократно побеждал на тестатонах
- Алексей Бурдин - основатель Kyiv Testers Meetup, неоднократно судья на тестатонах

++++
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/465880470%3Fsecret_token%3Ds-iC5op&color=%238c8c64&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
++++

++++
<a class="btn btn-primary" role="button" href="https://itunes.apple.com/ua/podcast/qaguild/id1350668092?l=ru&mt=2">Слушать в Itunes</a>
++++

*Спасибо патронам*:

Алиса Маркова, Алексей Игнатюк, Алексей Асанов, Дмитрий Панасюк, Борис Осипов,
Павел Скворцов, Эрик Халимов, Геннадий Мирошниченко, Михаил Судья, Виталий Закорчевный, Максим Денисов
Татьяна Грибок, Арина Аригри

{zwsp} +
Отдельное спасибо за монтаж звука Ярославу Пернеровскому