= Эпизод-25: Про сертификации и ISTQB
Сергей Пирогов
2018-11-23
:jbake-type: post
:jbake-tags: QAGuild, Podcast, Сертификации, ISTQB
:jbake-summary: Про ISTQB
:jbake-status: published

*Темы*:

- Когда получили свой первый сертификат?
- Краткая история ISTQB
- Почему ISTQB starter level есть у каждой собаки?
- Почему я не сертифицировался
- Какие бонусы дает сертификация?
- Advanced level ISTQB vs Foundation
- Куда идут деньги за сертификат?
- Про сертификационные туры
- Существует ли статистика получивших ISTQB в Украине по уровням?
- На сколько будет полезен сертификат при поиске работы в Европе и релокейте.
- Какие сертификаты есть кроме ISTQB?
- Selenium сертификации - фейк

*Гости*:

- Сергей Пирогов - заводила подкаста
- Ярослав Пернеровский - бог звука в подкасте
- Александра Ковалева - знает все про ISTQB
- Алексей Лупан - тренирует молодых тестировщиков

++++
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/533979162&color=%23948c6c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
++++

++++
<a class="btn btn-primary" role="button" href="https://itunes.apple.com/ua/podcast/qaguild/id1350668092?l=ru&mt=2">Слушать в Itunes</a>
++++

*Спасибо патронам*:

Алиса Маркова, Дмитрий Панасюк, Дмитрий Рудаков, Эрик Халимов, Марина Колесник, Алексей Асанов, Рома Маринский,
Сергей Солощенко, Игорь Перетятько, Максим Алферов, Марат Реймерс, Марина Колесник, Михаил Судья, Роман Поботин, Татьяна Грибок, Виталий Закорчевный

Отдельное спасибо за монтаж звука Ярославу Пернеровскому

Подписывайтесь на телеграмм канал - https://t.me/automation_remarks