= QA Guild Podcast: Святослав Логин о том как войти в секьюрити тестирование и защититься от веб-бандитов
Sergey Pirogov
2018-05-12
:jbake-type: post
:jbake-tags: QAGuild, Podcast
:jbake-summary: QA Guild Podcast
:jbake-status: published
:jbake-featured: true

Записали выпуск про интро в секьюрити тестрование.

*Темы:*

- Про безопасность в prom.ua
- С чего начать самоучке
- Интро в тулы для тестирования безопасности
- Как понять что вас взламывают
- Как писать код, чтобы вас не взломали
- Помогают ли "белые хакеры"
- Про метасплойт
- Сколько можно косить бабла на тестировании безопасности

*Гости:*

- Сергей Пирогов - заводила подкаста
- Ярослав Пернеровский - бог звука в подкасте
- Святослав Логин - QA лид в EVO company. Вошел в секьюрити сам

*Полезные ссылки*:

- https://haveibeenpwned.com/[Проверить были ли вы хакнуты]
- https://loginsvyat.wixsite.com/loginsvyat[Блог святослава]
- https://defcon.ru/tag/owasp/[Сайт с инфой по инструментам]
- https://www.youtube.com/watch?v=XcLI4cdWOCs&list=PLrTb7qqxTtPFxl8ZcAICTVXkSB34gCnma[Видосики про этичный хакинг]
- Промокод для QAFest - *QAGUILD*

++++
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/433437720&color=%23e0e01a&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
++++
https://itunes.apple.com/ua/podcast/qaguild/id1350668092?l=ru&mt=2[Слушать в Itunes]

*Спасибо патронам*:

Эрик Халимов, Виталий Закорчевный, Максим Денисов,
Павел Скворцов, Борис Осипов, Дмитрий Панасюк, Евгения Гнатюк,
Алексей Игнатюк, Илья Силантьев, Геннадий (без фамилии) ;)

Отлельное спасибо за монтаж звука Ярославу Пернеровскому

Вступайте в свободную https://qaguild-slack.herokuapp.com/[QA гильдию в Slack] и следите за новостями.