= QA Guild Podcast: О том, через какие курсы лучше "Войти в АйТи" (18+)
Sergey Pirogov
2018-06-25
:jbake-type: post
:jbake-tags: QAGuild, Podcast
:jbake-summary: QA Guild Podcast
:jbake-status: published
:jbake-featured: true

Символично в июне решили поговорить про вход в IT и "июней" после курсов.

*Темы:*

- Вступление (0:03)
- Представление гостей (0:30)
- Откуда взялся феномен “Войди в АйТи” (3:06)
- Про платные курсы (15:20)
- Горячие месяцы для обучения (17:35)
- Классический портрет успешного ваЙТишника (18:28)
- Пример “успешных” кандидатов (21:24)
- Рассизм по курсовому признаку (24:20)
- Сколько зарабатывают  на курсах и консультациях (28:30)
- Про курсы внутри компании (32:58)
- Почему имея знания, люди идут на платные курсы (40:28)
- Про днину на курсах (41:25 )
- Про мотивацию платить за ИТ курсы (54:55)
- Про успех входа в ИТ после курсов (58:40)
- Три требования к джуниору (1:07:13)
- Нужно ли идти в айти через тестирование или у нас уже и так дышать нечем? (1:08:48)
- Конкуренция среди соискателей (1:14:12)
- Проблемы, которые есть в самих курсах (1:22:20)
- Что выгоднее МАЙНИТЬ или КОСИТЬ БАБЛО на курсах? (1:35:00)
- Какой путь выбрать для работы в IT (1:37:30)

*Гости:*

- Сергей Пирогов - вошел в IT через галеру
- Ярослав Пернеровский - вошел в IT как нормальный человек
- Алексей Лупан - вошел в IT раньше всех и теперь учит других
- Артем Быковец - вошел в IT и сделал свои курсы для вайтишников
- Николай - вошел в IT через работу и решил остаться

++++
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/458125860&color=%238c8c64&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
++++

++++
<a class="btn btn-primary" role="button" href="https://itunes.apple.com/ua/podcast/qaguild/id1350668092?l=ru&mt=2">Слушать в Itunes</a>
++++

*Спасибо патронам*:

Алиса Маркова, Алексей Игнатюк, Алексей Асанов, Дмитрий Панасюк, Борис Осипов,
Павел Скворцов, Эрик Халимов, Геннадий Мирошниченко, Михаил Судья, Виталий Закорчевный, Максим Денисов
Татьяна Грибок, Арина Аригри

{zwsp} +
Отдельное спасибо за монтаж звука Ярославу Пернеровскому +
Рома Маринский и Игорь Перетятько получают благодарность за оформление таймкодов