= Эпизод-18: Размышления на тему роста и развития QA специалистов
Sergey Pirogov
2018-08-12
:jbake-type: post
:jbake-tags: QAGuild, Podcast, Conference
:jbake-summary: Размышления на тему роста и развития QA специалистов
:jbake-status: published

*Темы:*

- Зачем вообще рости?
- Кто такой QA это процесс или человек?
- Почему вдруг QA - это плохо и надо расти в какие-то AQA, SDET и прочую чепуху?
- Как развиваться?
- ПДП формы и план на пол года. Работает оно вообще?
- Платформа MTDV, чем она поможет?

*Гости:*

- Сергей Пирогов - заводила подкаста
- Ярослав Пернеровский - бог звука в подкасте
- Артем Задорожный - работает в германии, занимается развитием людей

++++
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/475948443&color=%238c8c64&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
++++

++++
<a class="btn btn-primary" role="button" href="https://itunes.apple.com/ua/podcast/qaguild/id1350668092?l=ru&mt=2">Слушать в Itunes</a>
++++

*Спасибо патронам*:

Алиса Маркова, Алексей Игнатюк, Алексей Асанов, Дмитрий Панасюк, Борис Осипов,
Павел Скворцов, Эрик Халимов, Геннадий Мирошниченко, Михаил Судья, Виталий Закорчевный, Максим Денисов, Татьяна Грибок, Арина Аригри, Олег Ильицкий, Роман Поботин

Отдельное спасибо за монтаж звука Ярославу Пернеровскому
