= QAGuild Эпизод-24: Марина Хомич о том, как нанимают людей и что важно при составлении резюме
Сергей Пирогов
2018-10-28
:jbake-type: post
:jbake-tags: QAGuild, Podcast, Собеседования
:jbake-summary: Про найм, резюме и рекрутинг
:jbake-status: published

*Темы*:

- Как стала рекрутером?
- Какие соц сети качать, чтобы тебя наняли?
- Как оформить резюме?
- Характерные ошибки на этапе HR интервью
- Как себя продать компании?
- Перегретый рынок труда, что с этим делать?
- Помогает ли HR бренд нанимать людей?
- Про не любовь к рекрутерам
- Чем отличается Senior рекрутер от Junior и Middle?
- Почему рекртеры наяривают после того как отклонил офер?
- Про зарплатные вилки и черные списки

*Гости*:

- Сергей Пирогов - заводила подкаста
- Ярослав Пернеровский - бог звука в подкасте
- Марина Хомич - рекрутер в компании Viber media

++++
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/520674489%3Fsecret_token%3Ds-T4ZH2&color=%23948c6c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
++++

++++
<a class="btn btn-primary" role="button" href="https://itunes.apple.com/ua/podcast/qaguild/id1350668092?l=ru&mt=2">Слушать в Itunes</a>
++++

*Спасибо патронам*:

Алекс Бондарь, Алиса Маркова, Дмитрий Панасюк, Дмитрий Рудаков, Эрик Халимов, Марина Колесник, Алексей Асанов, Рома Маринский,
Сергей Солощенко, Игорь Перетятько, Максим Алферов, Марат Реймерс, Марина Колесник, Михаил Судья, Роман Поботин, Татьяна Грибок, Виталий Закорчевный

{zwsp} +
Отдельное спасибо за монтаж звука Ярославу Пернеровскому

Подписывайтесь на телеграмм канал - https://t.me/automation_remarks