= QA Guild Podcast - первый русскоязычнй подкаст об автоматизации
Sergey Pirogov
2018-02-23
:jbake-type: post
:jbake-tags: QAGuild, Podcast
:jbake-summary: QA Guild Podcast официалочка
:jbake-status: published

Привет! Решил поделиться с вами новостью о запуске первого русскоязычного подкаста об автоматизации - http://automation-remarks.com/podcast[QAGuild podcast].

Идея создания такого формата зрела давно, но не хватало смелости взять и сделать. Так уж сложилось, что в сообществе
автоматизаторов и тестировщиков, которые работают в Украине, России, Беларуси и других странах, нету источника получения
новых знаний. Да, мы читаем одни и те же статьи и блоги, учимся на них, но большинство из них - англоязычные. И да, мы обсуждаем новости сферы на отраслевых конференциях.
Но не все любят и имеют возможность ходить на конференции. Проблема также в том, что многие боятся выступать перед аудиторией. Это может быть вызвано страхом публичных выступлений либо недостаточным уровнем подготовки материала. Поэтому я вижу подкаст идеальной площадкой для обмена опытом.

О чем это будет? Об автоматизации тестирования, трендах, TestOps, DevOps и о вот этом всем. Пилотные выпуски я публиковал
здесь - http://automation-remarks.com/2017/qa-guild-ep1/index.html[раз] и http://automation-remarks.com/2018/qa-guild-ep2/index.html[два].
Сейчас у подкаста появился свой http://automation-remarks.com/podcast[официальный сайт], на котором уже доступен
третий выпуск, посвященный DevOps.

Для более удобного прослушивания мы добавили официальные каналы в https://soundcloud.com/qaguild[soundcloud] и https://itunes.apple.com/ua/podcast/qaguild/id1350668092?l=ru&mt=2[itunes].
Впереди у нас запланировано много интересного и полезного.

Вы можете задаться вопросом, чем этот подкаст отличается от других?

Здесь вы можете влиять на выпуски и темы. Присоединяйтесь к нашему свободному https://qaguild-slack.herokuapp.com/[Slack сообществу] и предлагайте темы.
Особо стеснительные - пишите мне в личку :)

Надеюсь, подкаст принесет многим такую же пользу, как и этот блог. До встречи в эфире ;)

*P/S* Делать подкаст в разы сложнее, чем писать в блог. Если вам нравится то, что я делаю,
и вы хотели бы как-то поддержать эту инициативу, вы можете задонатить и https://www.patreon.com/automation_remarks[стать патроном].


