= Эпизод-22: Новости ушедшего лета
Сергей Пирогов
2018-10-20
:jbake-type: post
:jbake-tags: QAGuild, Podcast
:jbake-summary: Про собеседования
:jbake-status: published

*Темы*:

- О своих первых собеседованиях и работах
- Стоит ли заставлять кандидата писать код на бумажке? Если да, то какие задачи лучше всего?
- Лучшие способы на техническом собеседовании понять уровень кандидата
- O тестовых заданиях
- Про Github и stackoverflow аккаунты, или на какие-то другие открытые достижения
- Какие вопросы лучше задавать о будущем месте работы и должности? Какие вопросы будут засчитаны в плюс или минус?
- Стоит ли ходить на собеседования для тренировки.	Как отклонять офер?
- Какой фидбек нужно давать после собеседования?
- Про зарплаты
- Лучшие собеседования

*Гости*:

- Сергей Пирогов - заводила подкаста
- Ярослав Пернеровский - бог звука в подкасте
- Артем Никитин - тот самый, который балуется с GO
- Дмитрий Гуменюк - владыка Report portal

++++
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/514159989&color=%23948c6c&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
++++

++++
<a class="btn btn-primary" role="button" href="https://itunes.apple.com/ua/podcast/qaguild/id1350668092?l=ru&mt=2">Слушать в Itunes</a>
++++

*Спасибо патронам*:

Алекс Бондарь, Алиса Маркова, Дмитрий Панасюк, Дмитрий Рудаков, Эрик Халимов, Марина Колесник, Алексей Асанов, Рома Маринский,
Сергей Солощенко, Игорь Перетятько, Максим Алферов, Марат Реймерс, Марина Колесник, Михаил Судья, Роман Поботин, Татьяна Грибок, Виталий Закорчевный

Отдельное спасибо за монтаж звука Ярославу Пернеровскому

Подписывайтесь на телеграмм канал - https://t.me/automation_remarks