= Test Data Supplier - TestNG Dataprovider на стероидах
Sergey Pirogov
2018-02-11
:jbake-type: post
:jbake-tags: Java, Kotlin, TestNG
:jbake-summary: Про одну очень хорошую библиотеку для TestNG

Привет друг, сегодня хочу поделиться рецептом который поможет сделать тесты еще лучше.
На большинстве своих проектов я сейчас использую связку инструментов Java/Kotlin + TestNG +
Allure + Gradle. Ранее я уже писал о некоторых подходах, которые позволяют нам более
удобно http://automation-remarks.com/2017/json-randomizator/index.html[готовить данные для тестов],
http://automation-remarks.com/2017/kotlin-db/index.html[работать с базой данных] и http://automation-remarks.com/2017/selenide-allure-2/index.html[писать меньше аннотаций для Allure].

В этой заметке хочу рассказать о том как улучшить Dataprovider. Очень часто в тестах приходиться
оперировать различными наборами данных. В каких-то случаях данные проще захардкодить,
в каких-то тащить из внешних источников. В большинстве случаев для оптимизации кода и
параметризации я использую TestNG Dataprovider.

Давай возьмем для примера простой тест - логин форма с тремя полями и валидацией.

[source, java]
----
@Test(dataProvider = "Authentication")
public void errorMessageOnLoginWithBadCredentials(String email, String password, String errMsg) {
    User badUser = new User(email, password);

    at(LoginPage.class)
            .loginAs(badUser)
            .errorMessage
            .shouldHave(exactText(errMsg));
}

@DataProvider(name = "Authentication")
public static Object[][] credentials() {
    return new Object[][]{
            {" ", " ", "Username is required"},
            {"admin@gmail.com", "UserTest@123", "Login and / or password do not match"},
            {"admin@gmail.com", " ", "Password is required"},
            {"ololo@ololo.com", "admin", "Login and / or password do not match"}
    };
}
----

Очень простой сценарий, при различных сценариях, пользователю будут показываться разные сообщения об ошибке.
Здесь я применил простой Dataprovider, так как для каждой итерации у нас меняются лишь входные данные для теста.

Ну вроде как все отлично и вроде бы даже работает.

Есть ли что-то что можно улучшить? (люблю этот вопрос на собеседовании =))

Конечно, стоит посмотреть на уродливый дата провайдер. Вот этот *Object[][]* - то прям боль.
Учитывая что мы живем в 2018 году, пишем на Java 8, которая поддерживает Stream API и имеет хороший Collection API.
Двумерный массив объектов - это не серьезно!

И даже с помощью няшного Котлина нельзя особо улучшить ситуацию.

[source, java]
----
@DataProvider
fun data(): Array<Array<String>> {
   return arrayOf(
              arrayOf(" ", " ", "Username is required"),
              arrayOf("admin@gmail.com", "UserTest@123", "Login and / or password do not match"),
              arrayOf("admin@gmail.com", " ", "Password is required")
   )
}
----

Остается смириться и писать такой вот гавнокод, но нас самом деле ситуацию можно поправить с помощью библиотеки
https://github.com/sskorol/test-data-supplier[Test Data Supplier]. Ее автором является один мой друг - Сергей Король.

Я о ней знал давно но как-то попробовав ее еще на начальных этапах не особо проникся идеей. Пока на дня не
решил внедрить ее в один из новых проектов.

Подключение выполняется достаточно https://github.com/sskorol/test-data-supplier#usage[просто]. Однако там есть один нюансик -
для корректной работы требуется подключение DataProviderTransformer лисенер. Так вот - подключать
этот лисенер стоит либо через Gradle либо через TestNG xml. Подключение через аннотацию *@Listeners*
не даст желаемого результата. Учтите этот момент, я уже этот путь прострадал за вас=)

Собсвенно после подлючения вам становятся доступны все плюши этой библиотеки.

Можно легко переписать ваши унылые дейтапровайдеры на новый лад:

[source, java]
----
@DataSupplier
fun data(): Array<Array<String>> {
   return mapOf(
              User(" ", " ") to "Username is required"),
              User("admin@gmail.com", "UserTest@123") to "Login and / or password do not match"),
              User("admin@gmail.com", " ") to "Password is required"
   )
}
----

Тест в таком случае трансформируется в такую штуку.

[source, java]
----
@Test(dataProvider = "data")
fun errorMessageOnLoginWithBadCredentials(User user, String errMsg) {
    at(::LoginPage)
            .loginAs(user)
            .errorMessage
            .shouldHave(exactText(errMsg));
}
----

Все становится прям огненно круто. Есть один правда досандный момент - для полной поддержки как нужно
установить Idea плагин - *test-data-supplier-plugin*. Сама библиотека поддерживает разные навороты, о которых можно почитать в документации.

В общем всем рекоммендую как минимум посмотреть на эту библиотеку, как максимум прикрутить ее к себе в проект и пробовать.

Спасибо за внимание, надеюсь многим эта заметка поможет вывести тесты на новый уровень.












