= Как я блог на новую платформу двигал
Sergey Pirogov
2016-10-23
:jbake-type: post
:jbake-tags: Блог
:jbake-summary: История о переезде блога на JBake

История большого переезда на новую платформу. Я еще не писал история возникновения этого блога. Вот теперь я решил, что в предверии второй годовoщины его существования пора бы раскрыть все тайны.

Началось все еще в ноябре 2014 года, я просто хотел создать страничку **"О Себе"** и повесить ее где-то в интернете. Да, так как я не являюсь матерым девелопером в тот момент я не знал как же вообще это все делается. Честно говоря я даже не особо знал как эти все красивые сайты преобретуют вменяемые доменные имена.

Все началось с того, что я узнал о https://pages.github.com/[Github Pages] и залил туда какой-то невменяемый кусок **HTML** файла дабы попробовать как оно вообще работает.

Потом покопавшись в интеренете в поисках бесплатной платформы для создания блога, я случайно наткнулся на https://ghost.org/[Ghost blog]. Собственно она мне понравилась своим минимализмом и наличием большого количества шаблонов. Едиственный минус - для публикации статей на **Github Pages** требовалась установка какой-то станной утилиты написанной на **Python** - **buster**.

В общем овладев этим инструментарием **16 ноября 2014** года я выложил первую http://automation-remarks.com/first-post/index.html[заметку]. Собственно с того момента начался необратимый процесс =)

Вскоре я порчитал книгу https://www.amazon.com/Technical-Blogging-Expertise-Remarkable-Presence/dp/1934356883[Technical Blogging: Turn Your Expertise into a Remarkable Online Presence]. Там все достаточно грамотно расписано как сделать блог и на нем зарабатывать деньги, но попробовав использовать советы из книги, я понял, что все это фигня и нужно делать так как подсказывает интуиция. Долой рекламу и продакт плейсмент.

Таким образом, постепенно я выкладывал статьи о инструментах и подходах, которые я использовал на своих проектах. Блог постепенно обрастал ссылками на различные ресурсы, количество читателей постепенно росло. В среднем я публиковал одну заметку в неделю.

В скором времени заметки стали попадать в дайджесты на **DOU** и других площадках связанных с автоматизацией тестирования.

Но за этим всем стояла еще и техническая соствляющая. Я был жестко завязан на платформу, которая была завязана на версии **nodejs**, а так как я публиковал статьи с помощью **buster**, я еще и следил за версиями **Python** и чинил баги в этой адской утилите. В общем я мог писать и публиковать статьи только с одного ноутбука, который стоит у меня дома. Я был очень недоволен такой ситуацией, но альтернатив я найти не мог. Был **Jekyll** завязанный на **Ruby**, но я не хотел менять шило на мыло.

И вот буквально месяц назад листая ленту в **Twitter** я наткнулся на http://jbake.org/[**JBake**].

Естественно руки зачесались и начал двигать свой блог на эту платформу. Меня привлекло то, что все написано на **Java**, есть поддержка разных темплейтов: **Freemarker**, **Groovy**, **Thymeleaf** и **Jade**.

Более того, в интернете я нашел примеры того, как можно все это собирать с помощью любимого мною **Gradle**. Да, мне потребовалось примерно 3 недели, чтобы полностью перенести шаблон и весь сайт на **JBake**, но это того стоило.

Все по-прежнему хранится на **Github pages**, но теперь я не привязан к какой либо платорме, все что мне нужно - это **Java**.

Заметки можно писать в простых файлах формата **.adoc** или **.md**. Более того, с помощью **Travis CI** я получил полноценный процесс **Continuous Delivery**. Все что мне нужно это просто открыть **Intelij IDEA(!)**, написать статью или поправить какой-то файл, сделать **commit** и **push** и уже буквально через минуту новые изменения будут опубликованы без каких либо **down time**.

В целом я очень доволен, я потратил кучу времени на имплементацию, зато я узнал много нового.

Если вы задумываетесь над созданием своего сайта- визитки или блога, рекомендую посмотеть на **JBake**. Да придется немного попрограмировать, но усилия того стоят.








