= PhotoHack Odessa
Sergey Pirogov
2019-09-11
:jbake-type: post
:jbake-tags: Анонс
:jbake-status: published
:jbake-summary: PhotoHack Odessa — хакатон по созданию решения для креативной визуализации сообщений в мессенджерах.

PhotoHack Odessa — хакатон по созданию решения для креативной визуализации сообщений в мессенджерах.
Призовой фонд 200 000 гривен!

Новый хакатон от создателей популярного приложения Photo Lab. Участникам предстоит разработать креативное решение для визуализации текста, которое будет использовано в клавиатуре для мессенджеров. На входе программа получает текст и селфи пользователя, а возвращает изображение, которое можно использовать в дополнение к тексту или вместо него.
PhotoHack Odessa — это полная свобода творчества для разработчиков, дизайнеров, и просто креативных людей, которые не боятся экспериментов и готовы создавать новые форматы общения в мессенджерах.
Кого мы ждём: студентов технических и художественных вузов и креативных людей.

А теперь о призах:
1-е место 100 000 гривен
2-е место 65 000 гривен
3-е место 35 000 гривен

Помимо этого:
— Победители получат возможность сотрудничать с Photo Lab.
— Лучшие команды могут получить контракт на разработку от Photo Lab на сумму до 700 000 гривен
Прием заявок до 27 сентября
Спешите! Количество мест ограничено.
Регистрация:

telegram: http://bit.ly/2lV48G6
blog: http://bit.ly/2m1PRYn