= Тренинг Automation in Action Java for Juniors
Sergey Pirogov
2019-03-03
:jbake-type: post
:jbake-tags: Тренинг
:jbake-status: published
:jbake-summary: Тренинг для начинающих тестировщиков автоматизаторов

Многие просили и я делаю. Я решил попробовать провести один курс треннига по автоматизации на java для тех, кто очень хочет научиться, но не знает как это сделать, либо пробовал и не получилось.

Формат обучения - онлайн лекции
Дата начала - 30 марта 2019 года.

Программа:

Эта программа менторинга направлена на практическую составляющую. Этот курс расчитан для начинающих. Я ожидаю видеть ребят которые уже работают на проектах и смогут применять полученные знания у себя, не важно даже если вы сейчас работаете на позиции Manual QA, но хотите с чего-то начать.

Требования:

- Опыт работы на позиции QA engineer
- Знание консольных утилит git, linux commands

Чего не будет:

- Основ операционных систем
- Основ тестирования
- Много теории

Что будет:

- Основы Java
- Много практики

Создание проекта для тетирования REST API.

- подходы к автоматизации
- структура проекта
- управление тестовыми данными

Создание проекта для тестирования UI
- подходы к построению “фреймворка” на основе как проверенных инструментов, так и альтернативных типа HTMLElements 2
- подходы к управлению тестовыми данными
- репортинг

Настройка CI

Запуск тестов в Docker контейнерах - обзор существующих решений и работа с инструментами которые я использую каждый день
Все это с реальным демо проектом построенным на микросервисной архитектуре.

По длительности примерно 1.5 месяца. 1 лекция по выходным и 7 дней на выполнение домашнего задания.

Для записи на тренинг пишите на почту automationremarks@gmail.com либо в telegram @spirogov.

Не упустите свой шанс научиться писать автоматические тесты к началу лета.