= QAGuild S03E14: SecOps - второе пришествие
Сергей Пирогов
2020-10-05
:jbake-type: post
:jbake-tags: QAGuild, Podcast
:jbake-summary: Подкаст про DevSecOps
:jbake-status: published

++++
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay"
src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/902593087&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=false&show_teaser=true">
</iframe>
++++

Гости:

- Денис Якимов - специалист по безопасности

Темы:

++++
<ul class="timecoder">
  <li><a class="timecode">00:01:50</a> - Начало</li>
  <li><a class="timecode">00:01:54</a> - Как попал в айти?</li>
  <li><a class="timecode">00:04:57</a> - Зачем нужен SecOps</li>
  <li><a class="timecode">00:07:43</a> - Моделирование угроз</li>
  <li><a class="timecode">00:10:50</a> - Как сделать что бы секьюрити не замедляла ваше приложение</li>
  <li><a class="timecode">00:16:26</a> - С чего начать внедрение</li>
  <li><a class="timecode">00:26:03</a> - Кто этим может заниматься</li>
  <li><a class="timecode">00:29:28</a> - Где можно научиться</li>
  <li><a class="timecode">00:38:36</a> - В какое место пайплайна встраивать SecOps</li>
  <li><a class="timecode">00:43:38</a> - Чем сканировать Docker</li>
  <li><a class="timecode">00:47:49</a> - Как продать DevSecOps</li>
  <li><a class="timecode">00:51:40</a> - Про деньги</li>
  <li><a class="timecode">01:05:55</a> - Патроны</li>
</ul>
++++

https://t.me/automation_remarks[Telegram]

https://www.patreon.com/automation_remarks[Стать патроном]

Спасибо патронам:Tetiana Hrybok, Vitaly Fedrunov, Anastasiya Mazheika, Mykola Podolianiuk, Nikita Verbitsky, Олександр Пелих, Nikolay Georgievskiy, Vladimir Shukhov, Oleksandr Lazorenko, Andrey Lazuk, Арина Аригри, Oleksandr Shapovalov, Yevhenii Hrytsai, Kuptsov Ivan, Tiko, Oleksandr Demeniuk, Валентин Ханмамедов, Alex Hramovich
