= QAGuild S03E03: Про мобильные фермы
Сергей Пирогов
2020-03-15
:jbake-type: post
:jbake-tags: QAGuild, Podcast
:jbake-summary: Подкаст о том, как и зачем создавать мобильные фермы
:jbake-status: published

++++
<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/775022251&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
++++

Гости:

- Алексей Хурсевич - главный специалист по созданию мобильных ферм

Темы:

- 00:00:09 - Начало
- 00:01:41 - Гость
- 00:04:15 - Кому нужны мобильные фермы?
- 00:12:36 - Какие периферийные устройства используются при построении фермы?
- 00:16:40 - Сколько устройств я могу подключить к одному серверу?
- 00:19:11 - Как вы подбираете мобильные устройства для ферм?
- 00:21:08 - Какие преимущества и недостатки перед cloud провайдерами: Browserstack и Saucelabs?
- 00:23:58 - В чем основные ограничения ферм и cloud провайдеров в сравнении с устройствами на руках?
- 00:24:49 - Сколько стоит содержать мобильную ферму?
- 00:28:01 - С каким проблемами приходится сталкиваться в процессе эксплуатации?
- 00:31:15 - Как сделать стабильными беспроводной доступ к интернету для сотни девайсов?
- 00:33:51 - Где хранятся все устройства и как обеспечивается безопасность?
- 00:41:41 - Что из себя представляет конфигурация сервера: Ubuntu, MacOS?
- 00:48:27 - Может вспомните негативные случаи из опыта?
- 00:53:40 - В чем ваш интерес?
- 00:54:25 - Бекапы, дублирование надежность
- 00:59:36 - Возможно ли работать с устройствами удаленно, кому это может быть полезно в команде?
- 01:02:37 - Возможно ли полностью перевести мобильную автоматизацию в облако под управлением Kubernetes?
- 01:06:05 - Отчеты
- 01:09:45 - Appium vs Espresso ?
- 01:12:49 - Нужен ли паяльник?
- 01:16:32 - Патроны
- 01:24:55 - Финал