= QAGuild S03E03: Про мобильные фермы
Сергей Пирогов
2020-03-15
:jbake-type: post
:jbake-tags: QAGuild, Podcast
:jbake-summary: Подкаст о том, как и зачем создавать мобильные фермы
:jbake-status: published

++++
<iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/775022251&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
++++

Гости:

- Алексей Хурсевич - главный специалист по созданию мобильных ферм

Темы:

++++
<ul class="timecoder">
  <li><a class="timecode">00:00:09</a> - Начало</li>
  <li><a class="timecode">00:01:41</a> - Гость</li>
  <li><a class="timecode">00:04:15</a> - Кому нужны мобильные фермы?</li>
  <li><a class="timecode">00:12:36</a> - Какие периферийные устройства используются при построении фермы?</li>
  <li><a class="timecode">00:16:40</a> - Сколько устройств я могу подключить к одному серверу?</li>
  <li><a class="timecode">00:19:11</a> - Как вы подбираете мобильные устройства для ферм?</li>
  <li><a class="timecode">00:21:08</a> - Какие преимущества и недостатки перед cloud провайдерами: Browserstack и Saucelabs?</li>
  <li><a class="timecode">00:23:58</a> - В чем основные ограничения ферм и cloud провайдеров в сравнении с устройствами на руках?</li>
  <li><a class="timecode">00:24:49</a> - Сколько стоит содержать мобильную ферму?</li>
  <li><a class="timecode">00:28:01</a> - С каким проблемами приходится сталкиваться в процессе эксплуатации?</li>
  <li><a class="timecode">00:31:15</a> - Как сделать стабильными беспроводной доступ к интернету для сотни девайсов?</li>
  <li><a class="timecode">00:33:51</a> - Где хранятся все устройства и как обеспечивается безопасность?</li>
  <li><a class="timecode">00:41:41</a> - Что из себя представляет конфигурация сервера: Ubuntu, MacOS?</li>
  <li><a class="timecode">00:48:27</a> - Может вспомните негативные случаи из опыта?</li>
  <li><a class="timecode">00:53:40</a> - В чем ваш интерес?</li>
  <li><a class="timecode">00:54:25</a> - Бекапы, дублирование надежность</li>
  <li><a class="timecode">00:59:36</a> - Возможно ли работать с устройствами удаленно, кому это может быть полезно в команде?</li>
  <li><a class="timecode">01:02:37</a> - Возможно ли полностью перевести мобильную автоматизацию в облако под управлением Kubernetes?</li>
  <li><a class="timecode">01:06:05</a> - Отчеты</li>
  <li><a class="timecode">01:09:45</a> - Appium vs Espresso ?</li>
  <li><a class="timecode">01:12:49</a> - Нужен ли паяльник?</li>
  <li><a class="timecode">01:16:32</a> - Патроны</li>
  <li><a class="timecode">01:24:55</a> - Финал</li>
</ul>
++++