= Как я делал тихий компьютер дома
Сергей Пирогов
2020-05-03
:jbake-type: post
:jbake-tags: Telegram
:jbake-summary: История создания тихого компьютера дома
:jbake-status: published

Привет. Давненько я не писал заметок. В условиях карантина появилось время и решил рассказать историю создания тихого компьютера дома.
О рабочем месте я уже писал в своем https://t.me/automation_remarks/772[telegram канале].

Проблема заключалась в следующем. Сейчас я работаю из дома и у меня в качестве основного компьютера - системник и два монитора.
Наличие стационарного компьютера вместо ноутбука - это осознанный выбор: мощей больше, миников можно натыкать больше, стоит дешевле и система устаревает не так быстро.

Саму сборку компьютера я заказал в магазине, дабы особо не париться. Мне надо было иметь минмум 32GB RAM с нормальным процессором и возможностью при надобности
насыпать HDD/SSD. Обошлось это все в 800$. Сильно меньше, чем ноутбук подобных параметров.
В целом все работало как надо и радовало душу, до момента, как я начал проводить за этой системой больше пары часов на выходных.
Когда в доме было тихо, я заметил, что мой ящик сильно громко работает. На тот момент на вдув и на выдув у меня стояли
кулеры 120мм Be Quiet silent wings 3 в количестве 2х штук. Башенный кулер ноунейм  Vinga и Vinga блок питания на 500 Вт. Еще присутствовала видеокарта
Geforce 1050TI. Работало оно вот так:

++++
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/eY2tLSRUxlA" allowfullscreen></iframe>
</div>
++++

Из видео слышно, что шумит кулер видеокарты. Я копался в настройках, твиках и прочей требухе и оказалось, что именно в этой
серии видеокарты нельзя сбросить обороты кулера меньше 30%, больше можно, ниже нет. Ну вот такой нюанс.
Я решил поменять карту и поставил Nvidia geforce GTX 1650. Она поддерживает пассивный режим (кулеры не крутятся, если температура нагрева карты ниже 60 градусов).
Стало получше, но как только я убрал шумный элемент, вскрылись новые шумные части. На этот раз - башенный кулер процессора.
Я долго читал форумы, советовался с диванными экспертами и решил заменить кулер Vinga что-то там на Noctua. Я пересмотрел кучу обзоров
и остановился на https://hotline.ua/computer-kulery-i-radiatory/noctua_nf-p12/[NOCTUA NF-P12] PWM для башни процессора и 2х https://hotline.ua/computer-kulery-i-radiatory/noctua-nf-s12b-redux-1200/[NOCTUA NF-S12B redux-1200] для корпуса.
После этих манипуляций системный блок стал работать намного тише, но на фоне тишины оставался достаточно неприятный шелест
блока питания. Полечить проблемы простой заменой кулера не получилось, из-за того, что там была китайщина на 2pin(сейчас такой даже не найти).
Я долго сопротивлялся, но все же купил новый блок питания https://hotline.ua/computer-bloki-pitaniya/be-quiet-pure-power-11-600w-cm-bn298[be quiet! Pure Power 11 600W CM].

После всех манипуляций система начала работать очень тихо:

++++
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/c0lOVSh5GGw" allowfullscreen></iframe>
</div>
++++

В процессе переделки я продавал старые железки, поэтому заменил еще и корпус Vinga Smart 500W на https://www.fractal-design.com/ru/products/cases/define/define-mini-c/black[Fractal Design DEFINE MINI C].
У него стенки покрыты шумопоглощающим материалом, что улучшает общую картинку. В целом этих проблем можно было избежать
еще на этапе сборки, но шум системника меня особо и не тревожил, пока я работал за ним пару часов в неделю.
В целом с учетом продажи старого железа и покупки нового я доплатил примерно 200$.

Вот такая история. Если у вас есть интересные истории создания комфортного рабочего места, заходите в наш https://t.me/automation_remarks_flood[чатик] - интересно будет обсудить.
