= QA Guild Podcast EP-1: Тестирование микросервисов
Sergey Pirogov
2017-12-30
:jbake-type: post
:jbake-tags: Podcast
:jbake-summary: QA Guild Podcast
:jbake-status: published
:jbake-featured: false

Доступен первый выпуск подкаста о тестировании микросервисов

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/fyrg7QlNR9Y" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
++++

В этом выпуске обсуждались подходы и инструменты которые применяются
для тестирования приложений на основе микросервисной архитектуры.

Гости:

*Дмитрий Гуменюк* - владыка репорт портала

*Николай Алименков* - знает все о микросервисах

*Ярослав Пернеровский* - обладает диванной экпертизой в области тестирования
микросервисов

*Александр Романов* - об микросервисах знает не понаслышке

*Сергей Пирогов* - видел микросервисы еще до того как это стало мейнстримом

Полезные ссылки:

https://martinfowler.com/articles/microservice-testing/[Статья Мартина Фаулера]

https://swagger.io/[Swagger]

https://www.getpostman.com/[Postman]

https://github.com/gaia-adm/pumba[Pumba]

https://github.com/Netflix/SimianArmy/wiki/Chaos-Monkey[Chaos-Monkey]

https://docs.pact.io/[PACT]

https://cloud.spring.io/spring-cloud-contract/[Spring cloud contract]

https://github.com/swagger-api/swagger-codegen[Swagger codegen]

Мы получили достаточно много положительных отзывов, поэтому первым выпуском все не ограничится.

Вступайте в свободную https://qaguild-slack.herokuapp.com/[QA гильдию в Slack] и следите за новостями.