= QA Fest 2017: ретроспектива
Sergey Pirogov
2017-09-24
:jbake-type: post
:jbake-tags: Конференции
:jbake-summary: Отзыв о посещении конференции QAFest 2017
:jbake-status: published

В эти выходные посетил конференцию QAFest 2017 и пока в голове свежи воспоминания, решил
написать свой отзыв. Конференция проходит уже 4й год подряд в Киеве. В этом году конференцию посетило больше 800
человек, что является абсолютным рекордом по посещению конференций по тестированию в Украине.

**Об организации:**

Как и в прошлые годы конференция проходила в БЦ "Космополит". Нужно отметить, что несмотря на такой масштаб, уровень организации находиться на высоком уровне:
еды хватало всем, можно было попить чай кофе и печеньки в неограниченном количестве. Конференция еще с самого начала задумывалась
как фестиваль тестирования, атмосфера способствовала общению и новым знакомствам.

**О докладах:**

Как бы там ни было, но на конференцию люди приходят послушать интересные доклады с целью узнать что-то полезное для себя.
В этом году я непостредственно учавствовал в формировании сетки докладов, так как был участником программного коммитета.
Я отвечал за подбор докладов в поток автоматизации тестирования. Хочу отметить, что - это достаточно интересный опыт, так
как есть возможность посмотреть закулисы конференции.
Из докладов которые мне понравились можно отметить следующие:

- **Алексей Буль**. Тестирование геолокационных систем
  Достаточно интерсный опыт с наводками на ресурсы и инструменты которые помогают в тестировнии ГИС.

- **Николай Алименков**. Разработчик + тестировщик=качество
  Очередной Колин доклад о пользе взаимодействия разных ролей в команде.

- **Дмитрий Гуменюк**. ReportPortal.io
  Димын доклам в первую очередь запомнился фразами "Сухие логи" и "Грязный зайчик". В целом очередной доклад про
  новые возможности http://automation-remarks.com/2017/report-portal/index.html[RP].

- **Александр Неделяев**. Тестирование и мониторинг производительности фронтенда с помощью sitespeed.io
  Самый интересный и полезный доклад для меня. Саша показал основные возможности инструмента, привел хорошие примеры.
  Я с помощью этой штуки тестировал свой блог, но инструмент обрел дополнительные фичи.

**О себе:**

Как и в http://automation-remarks.com/qafest-2016-rietrospiektiva/index.html[прошлом году]
я выступал с двумя докладами: `Test Automation Pazzlers` и докладом который я назвал `Kotlin без маркетинга`. Хочу отметить,
что пазлеры, который мы сделали вместе с Ярослав Пернеровским стали украшением первого дня. Спасибо Ярику, что согласился и помог воплотить мою идею в жизнь.
Моя идея воплотилась в полной мере. Когда появиться видео, рекомендую посмотреть,
но камера не передаст той атмосферы которая царила в зале. Говорят я там даже матерился =))
Доклад о Котлине был тоже харош, но я его заведомо сделал не таким задорным и драйвовым как обычно. После первого
дня не было сил. Но все же на парочку перлов я наработал. Своими выступлениями я полностью доволен.

**В целом:**

Лично для меня конференция прошла очень круто, много живого общения и новые знакомства со старыми друзьями. Я встретил старых знакомых с которыми я работал и общался в Харькове.

**О будущем:**

В процессе общения я постоянно спрашивал мнение других участников. Говорят, что среди докладов на которые я не ходил, были унылые выступления, но
в целом всем все понравилось. На закрытии организаторы сказали что QAFest 2018 будет проходить следующей осенью, а
это означает, что мы снова соберемся вместе в 2018 годы, чтобы обсудить новости из мира тестирования.

На этом у меня все. Я пошел отдыхать и готовиться к еще двум очень значимым для меня конференциям, на которых
я буду выступать этой осенью. Подписывайтесь на мою https://www.facebook.com/automationremarks/[страницу в фейсбуке], чтобы оставаться
в курсе событий. Па-па...

