= Как мы перешли на Selenoid
Sergey Pirogov
2017-07-24
:jbake-type: post
:jbake-tags: Java
:jbake-summary: История нашего перехода на Selenoid
:jbake-status: published

Наконец-то я добрался до написания заметки о https://github.com/aerokube/selenoid[Selenoid]. Я расскажу о том как и зачем мы его внедрили и что это
нам дало.

Еще со времен когда я только вошел в IT в целом и мир автоматизации в частности, мы знали таком инструменте как Selenium Grid. Достаточно полезная
штука и по всей видимости очень популярная, так как заметка о http://automation-remarks.com/nastraivaiem-selenium-grid-za-5-minut/index.html[настройке грида]
является одной из самых читаемых.
Сам грид штука прикольная, но очень не стабильная. Многие проекты и компании научились танцевать с бубном и настривать грид так, чтобы он не падал.
Скажем ребята из Яндекса наваяли свой https://www.youtube.com/watch?v=ULcE3993cZg[грид роутер], ребята из Альфа-лаборатории наваяли свой
https://habrahabr.ru/company/alfa/blog/331434/[кластер]. Когда же пришло наше время к настройке инфраструктуры для запуска UI тестов, мы решили не
изобретать велосипед и взять готовое решение под названием **Selenoid**.

Почему именно Selenoid?

Все достаточно просто - его очень просто настроить, там есть докер и хорошая производительность.

Я уже давно играюсь с докером. На одном из проектов мы внедрили http://automation-remarks.com/ganiaitie-tiesty-v-kontieinierie-s-testcontainers/index.html[тест контенеры]
на другом просто запускали браузер в докере. На текущеп проекте мы изначально хотели запускать тесты в безголовом хроме, но в тот момент эта функциональность
работала не так хорошо как бы нам хотелось, да и дебажить тесты в невидимом решиме не так уж и круто.

Selenoid же был решением, которое очень хотелось попробовать в реальной работе. Реальные плюс состоит в том, что настроить его очень просто  при
помощи http://aerokube.com/cm/latest/[Configuration Manager].

Реально выполняете пару команд:

----
$ curl -L -o cm https://github.com/aerokube/cm/releases/download/1.2.3/cm_linux_amd64
$ chmod +x ./cm
$ ./cm selenoid start --vnc
$ ./cm selenoid-ui start
----

и у вас уже все настроено и работает. Реально у нас это все заняло 10 минут (наша версия докера не подходила и нам его пришлось обновлять) =)

Всего через неделю использования, мы забыли о том, что такое локальный запуск браузера. При наличии VNC можно абсолютно спокойно дебажить тесты прямо на удаленной
машине. Огромным плюсом из-за которого я вообще посмотрел в сторону Selenoid является запуск контейнера по запросу и повторяемость окружения.
У вас всегда известна версия браузера в котором буду бежать тесты. Всегда создается новый контенер под новую сессию. Больше нету неожиданных автообновлений
хрома или файрфоркса. Более того мы полечили синдром "А у меня локально работает!", так как все запускают тесты только удаленно.

Минусы есть?

Пока что у нас почему-то проскакивает ошибка `Could not create remote session`. Случается она редко и лечится банальным перезапуском, но все же не приятно.
Да и проблема скорее всего у нас в коде. Еще в контейнере не работает команда driver.manage.window.maximize(), поэтому приходиться ставить размер окна явно.

Мы используем Selenide (на Kirk мы пишем пока только один проект) и написали свой `SelenoidDriverProvider`:
Специально приведу пример кода, так как многи часто задают один и тот же вопрос, а как настроить. Так как у Selenide с документацией скажем откровенно
"проблемы", можете опираться на пример ниже:

----
public class SelenoidWebDriverProvider implements WebDriverProvider {
  @Override
  public WebDriver createDriver(DesiredCapabilities capabilities) {
    DesiredCapabilities browser = new DesiredCapabilities();
    browser.setBrowserName("chrome");
    browser.setVersion("59.0");
    browser.setCapability("enableVNC", true);

    try {
      RemoteWebDriver driver = new RemoteWebDriver(
              URI.create("http://172.28.28.217:4444/wd/hub").toURL(),
              browser
      );
      driver.manage().window().setSize(new Dimension(1280, 1024));
      return driver;
    } catch (MalformedURLException e) {
      throw new RuntimeException(e);
    }
  }
}
----

В коде это можно использовать так:

----
Configuration.browser = "com.tests.utils.SelenoidWebDriverProvider"
----

В целом я очень доволен и мы получаем реальный профит. Что мы еще не пробовали, так это обновляться. В новой версии Selenoid добавили возможность
сетить имя для контейнера, чтобы можно было по имени легко определить нужную VNC сессию. Вот это мы пока не попробовали, так что, все еще гадаем на какой табке кино смотреть =)

**P/S** Приятная новость - автор Selenoid будет выступать с докладом на конференции http://qafest.com/[QAFest], поэтому у всех посетителей
будет возможность не только послушать доклад, но и познакомиться лично. Собственно это я и собираюсь сделать. Я тоже буду там
выступать, но об этом я напишу уже в следующей заметке.



