= Сообщество тестировщиков Automation remarks
Сергей Пирогов
2021-09-12
:jbake-type: post
:jbake-tags: Telegram
:jbake-summary: Сообщество Automation remarks
:jbake-status: published


Привет!

Cегодня хочу поговорить с вами на тему комьюнити для тестировщиков.

Как и в любой сфере, среди тестировщиков существует куча различных комьюнити. 
Раньше они организовывались в скайпе.

К примеру, "QA клуб Харьков" и "QA Automation чат". Там было по 300-400 человек.
Люди обменивались разной информацией, общались. В Харькове на основе клуба проходили митапы.
Потом скайп начал отмирать и его заменил Slack. Slack 
позволял держать большое количество людей и там были каналы, где можно было разделить общение по темам,
наблюдался определенный рост таких сообществ. Их было огромное множество. Я состоял в QAGuild слаке, в 
котором на пике состояло 3000 человек.
Но у слака были свои проблемы: он плохо работал на телефоне, жрал батарейку и память. Началось бурное развитие telegram. В 2018 году я завел свой канал и начал публиковать 
интересные новости мира тестирования и IT в целом. Постепенно активность в Slack поутихла и все перешли на телеграмм.
Сейчас, я вижу, самые живые и мощные сообщества тестировщиков находятся именно в телеграмме.

Однако у всех этих сообществ, чатов, каналов была и есть общая проблема.

Все они были созданы на хаотичной основе, поэтому в них изначально не было задумано никой модерации, правил и ограничений.
Как правило, они создавались энтузиастами, c благими целями и поэтому в принципе это и не требовалось.
Полная свобода и отсутствие ограничений положительно влияют на творческий процесс, однако все ломается в тот момент, когда отдельные участники
начинают нарушать спокойствие других участников, прикрываясь теми самыми правилами свободного общества. Токсичность начинает захватывать чат, тред, группу 
и убивать у людей любое желание проводить там время. Это проблема, ведь на 1000 участников всегда найдется парочка токсиков, которые начинают портить атмосферу.
Именно так было и с телеграмм-группой, которая прикреплена к моему каналу https://t.me/automation_remarks. 
После всех этих наблюдений я пришел к выводу, что свобода должна быть контролируемой и без модерации никакой чат с более чем пятью участниками не возможен.
Я решил провести эксперимент и завел закрытый чат для тестировщиков https://t.me/automation_remarks_bot[@automation_remarks_bot] и ввел символическую плату - 2$.
Особенностью чата является то, что здесь удалось создать атмосферу открытости и взаимопомощи. Членский взнос отлично работает как фильтр от неадеквата и совсем начинающих. 
Здесь вы можете задать вопрос и точно получите квалифицированный совет. На основе чата удалось положить начало "Вечерам грязи" и ежемесячному дайджесту новостей, который выходит на моем https://www.youtube.com/channel/UCHtyBZ2XbtsRmNiAxh48RGg[Youtube канале]. 
Если вы давно хотели найти ламповое комьюнити, где могли бы черпать знания и делиться идеями, welcome https://t.me/automation_remarks_bot[@automation_remarks_bot]

Что вы там можете найти:

- 📌 регулярные посты, новости, ссылки на закрытые YouTube стримы и ранний доступ к подкасту;
- 📌 1 раз в месяц будем собираться и обсуждать новости индустрии (сначала онлайн, а как попустит корону, попробуем делать митапы оффлайн);
- 📌 закрытый чат с модерацией.
 
Чтобы присоединиться к сообществу, подписывайся на бот https://t.me/automation_remarks_bot[@automation_remarks_bot].
