= Сообщество Automation remarks
Сергей Пирогов
2020-01-18
:jbake-type: post
:jbake-tags: Telegram
:jbake-summary: Сообщество Automation remarks
:jbake-status: published

Пришло время обнуляться и сделать анонс бота https://t.me/automation_remarks_bot[@automation_remarks_bot] и привязанного к нему чата. Я решил создать его с целью развития комьюнити и создания места, где люди говорят о тестировании без флуда, рекламы и токсичных участников. Места, где люди не стесняются задавать вопросы и делиться опытом (необязательно успешным).  

Что там будет:

- 📌 регулярные посты, новости, ссылки на закрытые YouTube стримы и ранний доступ к подкасту;
- 📌 1 раз в месяц будем собираться и обсуждать новости индустрии (сначала онлайн, а как попустит корону, попробуем делать митапы оффлайн);
- 📌 закрытый чат с модерацией.

Что будет с бесплатным каналом?
Он продолжит свое существование на прежней основе, уменьшится частота постов. 

Чтобы присоединиться к сообществу, подписывайся на бот https://t.me/automation_remarks_bot[@automation_remarks_bot]. Первая неделя - бесплатно, ты сможешь читать новости, потом нужно будет стать патроном 💸. Всем мир🙌
