name: Site CI

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show content
        run: ls -la
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build the site
        run:  ./gradlew clean jbake
      - name: Commit files
        run: |
            - git config user.name "${{ secrets.GH_USER_NAME }}"
            - git config user.email "${{ secrets.GH_USER_EMAIL }}"
            - git add -A ./build/jbake/*
            - git status
            - git commit -m "Deploy to GitHub Pages"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}