name: Site CI

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          ref: source

      - name: Build the site
        run:  ./gradlew clean jbake

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: master # The branch the action should deploy to.
            FOLDER: build/jbake # The folder the action should deploy.